# Generated by Django 4.2.11 on 2024-04-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Заказчик'), ('executor', 'Исполнитель'), ('guest', 'Гость')], default='guest', max_length=20, verbose_name='Роль'),
        ),
    ]
