# Generated by Django 4.2.11 on 2024-04-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='posts_images', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_details',
            field=models.TextField(blank=True, help_text='Введите ваши контактные данные.', max_length=200, verbose_name='Контактные данные'),
        ),
    ]
