# Generated by Django 4.2.11 on 2024-04-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_photo_alter_user_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Имя'),
        ),
    ]
