# Generated by Django 4.2.11 on 2024-04-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Описание заказа'),
        ),
    ]
